### ISSUE TITLE
Insert MQTT Messages into Database

### ISSUE THREAD

**Issue by wiserdivisor** [sabuhish/fastapi-mqtt#13]
As requested by @sabuhish I have added this here as an issue.
Here's the [link](https://github.com/tiangolo/fastapi/issues/1422#issuecomment-733939899) to my original post.

TL;DR: I was not able to implement the insertion of MQTT messages received by fastapi-mqtt into my database.
I figured a work-around using **paho-mqtt** in another python script that makes a post request to the API, but of course,
it's not nearly as graceful as it would be if fastapi could do this all by itself.
i.e. Connecting -> Subscribing -> Receiving -> **Insert to DB**

P.S. : Thanks fastapi-mqtt devs for making this library. Your work is witnessed and appreciated!!!

**Comment by sabuhish** [comment]
@wiserdivisor Thank you for posting here! Well I have followed your code this code below has to have some fixes:
```@mqtt.on_message()
async def message(client, topic, payload, qos, properties, db :Session = Depends(get_db)):
    data_list = payload.decode().split()
    data = {'fduid':'FDU-'+topic[-6:],
            'evnty':data_list[0],
            'tstmp':data_list[1],
            'locur':data_list[2]}
    print(data)
    return create_event_mqtt(db=db, event=data)
```
the `message` function is the handler  I am registering it as a callback inside the module. It supposes to have only four parameters client, topic, payload, qos, properties. I am seeing you are using db also as a parameter. Can you please remove this argument and try again.

**Comment by sabuhish** [comment]
@wiserdivisor Well, I tested mqtt with this [boilerplate](https://github.com/Turall/FastApi-boilerplate) of fastapi everything works quite fine I was able to receive a message from the subscribed topic and insert to the database. I was using gino orm which core sqlalchemy.

**Comment by wiserdivisor** [comment]
@sabuhish Thank you for addressing my issue!
Your solution has worked for me. Please see my code below.
I have modified it as you asked :
```
@mqtt.on_message()
async def message(client, topic, payload, qos, properties):
    data_list = payload.decode().split()
    data = {'fduid':'FDU-'+topic[-6:],
            'evnty':data_list[0],
            'locur':data_list[1],
            'tstmp':data_list[2]}
    db = SessionLocal()
    returned = event_crud.create_event_mqtt(db=db, event=data)
    print(returned)
```

I added `db = SessionLocal()` in the function body because I didn't know where else to put it.
And it worked none the less! But please do tell me if my code can be any better.
Thanks for your help! It's a priviledge nice to get help from the devs themselves!
Now I won't have to use another PY script for posting the messages! Very Nice :100:

**Comment by sabuhish** [comment]
@wiserdivisor Cool! Happy to hear this.

Well, for your case I have no idea what ORM do you use. We have been using this boilerplate for development and production, it has been successful for us. We used Gino-ORM for database queries. This might be a good solution for you too. Enjoy! :-)
