### ISSUE TITLE
There is a typo in the MQQTConfig class

### ISSUE THREAD

**Issue by JenspederM** [sabuhish/fastapi-mqtt#16]
Hi guys. 

Love the work you are doing - you wanted to inform you, that you have a typo in the MQQTConfig class. This should be named MQTTConfig right? :-)

Best regards.

**Comment by sabuhish** [comment]
Hi there! 

Thank you! :) yeah, you are right, we misplead that. If you want and able to send PR we would welcome it. you can read guidlines for contributing. (Contribute)[https://github.com/sabuhish/fastapi-mqtt/blob/master/CONTRIBUTING.md]
