### ISSUE TITLE
got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by ngochieu642** [sabuhish/fastapi-mqtt#17]
- When I run the app using uvicorn directly, everything is fine
- However when I run it using an external file, this raises the error

> got Future <Future pending> attached to a different loop

I made a repository to describe my situation, could you give it a look.
https://github.com/ngochieu642/issue-3-fastapi-mqtt

**Comment by sabuhish** [comment]
We had a tough week. I was not able to check it. This is an interesting behavior, thank you for reporting. I am doing my best to produce a solution.

**Comment by ngochieu642** [comment]
Thank you for your hard work, it really made working with mqtt much smoother. 

I did try to look at the issue, and it seems the problem came from gmqtt connection called with `loop = asyncio.get_event_loop()` at some point. The [docs](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) states that:

> If there is no current event loop set in the current OS thread, the OS thread is main, and set_event_loop() has not yet been called, asyncio will create a new event loop and set it as the current one.

 I think it should be :
  - A loop passed down from who call the loop
  - `asyncio.get_running_loop()`

But I am not that familiar with asyncio to come to a conclusion

I would like to contribute to this project, is there anything I can do?

**Comment by sabuhish** [comment]
@ngochieu642  Thank you for following up!

Well, I will look up this search a bit more. But before I want to give a solution for your case, so you can work around with fastapi-mqtt.

I have used  tiangolo's image for it:

```
FROM  tiangolo/uvicorn-gunicorn-fastapi:python3.7

COPY . /app
WORKDIR /app

RUN apt-get update -y &&  pip install --upgrade pip &&  \
    pip install -r requirements.txt 
  
 ```
running in a container env:

```docker build -t fastapi-mqtt .
docker run  -p 8000:80 fastapi-mqtt
```

for mqtt broker I used mqtt.flespi.io in order to check connection `https://flespi.io/` and everything works quite fine.

Thank you indeed, I will try my best to see what happens.

**Comment by skylli** [comment]
I get the same issue when i run my fastapi and fastapi-mqtt on windows.

**Comment by sabuhish** [comment]
Can you paste your code here, how exactly you run uvicorn with fastapi-mqtt ?

**Comment by sabuhish** [comment]
The solution would be using gunicorn with uvicorn workers. As you move to production, it is not best practice to use uvicorn in the production. You should be using gunicorn.

Read more here:
https://www.uvicorn.org/deployment/

I have already provided an answer, second one I will suggest with gunicorn calling python's subprocess module.

Create start.sh file
```
#!/bin/bash

# Start Gunicorn processes
echo Starting Gunicorn.
exec gunicorn --reload app.main:app   -k uvicorn.workers.UvicornWorker  --bind 0.0.0.0:8000
```
You can pass other configs as well, I simplified it.

inside `run.py`
``` 
if __name__ == '__main__':
    subprocess.call(['sh', './start.sh'
subprocess.call(['sh', './start.sh'])
```

As a solution found for this case I am closing this issue.
