### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by jruokolainen** [sabuhish/fastapi-mqtt#20]
Hi, I tried running the example code and got the following error: 
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 1883, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 1883)
I'd like to convert my http API to a mqtt for better IoT support but this happens. 
rant it with uvicorn main:app --reload command thx in advance

Running with hyper corn gives this error: 
../fastapi_mqtt/fastmqtt.py", line 78, in __init__
    log_info = logger
NameError: name 'logger' is not defined

**Comment by jruokolainen** [comment]
Actually it worked once I changed the broker host in the config, but as for improvement suggestions a topic schema automatic docs would be great

**Comment by jruokolainen** [comment]
Default broker (localhost) didn't work my bad

**Comment by jruokolainen** [comment]
Also needed to update mosquitto (osX) to get it working

**Comment by sabuhish** [comment]
Cool glad that you fixed it! :) It is not designed for auto docs style actually.
