### ISSUE TITLE
Multiple subscriptions with multiple workers

### ISSUE THREAD

**Issue by maru-sama** [sabuhish/fastapi-mqtt#24]
Hello,

I just recently switch to fastpi-mqtt for some testing. While developing with a single worker everything works fine as soon as I put the code in a docker instance I noticed that it has issues with multiple workers though. Per default tiangolo/uvicorn-gunicorn-fastapi creates 8 worker processes for me, as a result I have 8 subscriptions as well and if a change is published my on_message method is called 8 times which is not ideal. Either I am missing something or there are issues with multiple workers.

**Comment by sabuhish** [comment]
Hello, can you paste your code here, how exactly do you run unicorn with fastapi-mqtt in docker container ?

**Comment by maru-sama** [comment]
The code is pretty straightforward and registers a subscription during startup. The standard uvicorn-gunicorn-fastapi image automatically scales the number of worker processes depending on the number of physical CPUs. As a result in my case the 4 processes are created and hence I have 4 subscriptions. I did not notice this during programming since in this case only ONE process is started. In the meantime I changed to code and made due without subscriptions, since I guess there is a general issue with subscriptions and multiple processes, that cannot be easily fixed.

**Comment by ruem2802** [comment]
@maru-sama I am the same issue, What is the solution here?

**Comment by maru-sama** [comment]
The solution I came up with for my specific case was not to use any subscriptions at all. If you require this an alternative is to configure the docker image to only run one worker process.

**Comment by ruem2802** [comment]
@maru-sama  I want to run only worker process with mqtt but want to run api with 4 process.
Can I configure the docker to do that?

**Comment by ruem2802** [comment]
@maru-sama  i have a other solution: We can run with command : 
uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4 (We user  --workers for 4 process)

**Comment by maru-sama** [comment]
Is the global really global across all running processes, I somehow doubt that.

**Comment by ruem2802** [comment]
with api only one , i checked

Vào Th 4, 22 thg 9, 2021 vào lúc 19:29 Michael Guntsche <
***@***.***> đã viết:
