### ISSUE TITLE
Add an ability to move mqtt handlers outside main

### ISSUE THREAD

**Issue by sskorol** [sabuhish/fastapi-mqtt#29]
Hi @sabuhish, thanks for the great library!

I'm wondering if it's possible to move mqtt handlers to a different package rather than putting everything into main?

Usually, when you build a production-level code, you organize it into logical packages, e.g. api, model, etc. FastAPI has a good concept of APIRouter as an example.

If I run a sample from the README within a script where FastAPI instance is created, everything works as expected. But when I try to move mqtt code somewhere else (outside main), the app is failing at the start:
```shell
ERROR:    Traceback (most recent call last):
  File "/project_path/.venv/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/project_path/.venv/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/project_path/.venv/lib/python3.8/site-packages/starlette/routing.py", line 598, in startup
    await handler()
  File "/project_path/app/main.py", line 77, in startup
    await mqtt_client.mqtt.connection()
  File "/project_path/.venv/lib/python3.8/site-packages/fastapi_mqtt/fastmqtt.py", line 129, in connection
    await self.client.connect(self.client._host,self.client._port,self.client._ssl,self.client._keepalive,version)
  File "/project_path/.venv/lib/python3.8/site-packages/gmqtt/client.py", line 230, in connect
    await self._connected.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-3' coro=<LifespanOn.main() running at /project_path/.venv/lib/python3.8/site-packages/uvicorn/lifespan/on.py:84>> got Future <Future pending> attached to a different loop
```
As far as I understood, mqtt instance is running in a different event loop for some reason if it's located in the other package? Is there any workaround for that?

P.S. I run the code via uvicorn.

**Comment by yashveerjain** [comment]
hi @sskorol have you found out the solution for this? or is there any alternative way to this problem?
thanks

**Comment by sskorol** [comment]
@yashveerjain I believe I found some solution. But it was a while ago. If I find source code, I'll share it here.

**Comment by sabuhish** [comment]
Hi @sskorol, sorry for being late, I was not able to look at the library for some time. I have updated and released a new version of the library. To your question, the library does not totally depend on the main file, if you initialize the fastapi in main and try to import the app to where you would run your mqtt instance. 
I am closing the issue, as there is a solution already, feel free to open if have any, please consider moving 1.0.0 version if you have chance of course, thanks :)
