### ISSUE TITLE
can't connect to Hivemq Websocket

### ISSUE THREAD

**Issue by panupong-sudj** [sabuhish/fastapi-mqtt#39]
Hi! i try to connect Hivemq Websocket useing uvicorn --reload but it can't connect 
![image](https://user-images.githubusercontent.com/78843048/175508070-9cf97d29-d884-4395-8ce2-2c296105dbb7.png)
here is my code
![image](https://user-images.githubusercontent.com/78843048/175508469-6e37b193-74e6-4214-8968-b6204f0eee12.png)

**Comment by sabuhish** [comment]
Hi, unfortunately WebSocket protocol is not supported.

**Comment by panupong-sudj** [comment]
> Hi, unfortunately WebSocket protocol is not supported.

oh i see thank you sabuhish

**Comment by goldyfruit** [comment]
It would be a nice to have. :+1:
