### ISSUE TITLE
Pass MQTT client to a router

### ISSUE THREAD

**Issue by goldyfruit** [sabuhish/fastapi-mqtt#40]
Hi,

I would like to know if it is possible to pass the MQTT client initiated by `init_app()` to a router that is included by `included_router()`?

```python
mqtt_config = MQTTConfig()
mqtt = FastMQTT(
    config=mqtt_config
)

app = FastAPI()
mqtt.init_app(app)

app.include_router(activities.router)
```

I would like to access the `@mqtt.on_message()` decorator from the `activities.router` routes to read the message only when a specific route is called.

Thanks for your help.

**Comment by Angatupyry** [comment]
I think you should call the `@router.on_event("startup")` method in your activities.router file and make the connection there as follows. 

```
@router.on_event("startup")
async def startup():
    try:
        await mqtt.connection()
    except Exception as e:
        raise e
```
Your decorators clearly have to be in your route file.

**Comment by goldyfruit** [comment]
Thanks.

**Comment by tomliptrot** [comment]
I'm struggling with this as well. If I follow @Angatupyry 's advice, how do you access the mqtt object inside activities.router without circular dependencies?

app.py
```
import activities

mqtt_config = MQTTConfig()
mqtt = FastMQTT(
    config=mqtt_config
)

app = FastAPI()
mqtt.init_app(app)

app.include_router(activities.router)
```
activities.py
```
from fastapi import APIRouter
from .app import mqtt

router = APIRouter()

@router.on_event("startup")
async def startup():
    try:
        await mqtt.connection()
    except Exception as e:
        raise e
```

Gives an error:`ERROR:    Error loading ASGI app. Could not import module "app".`
