### ISSUE TITLE
MQTT subscription topic matching does not conform to spec

### ISSUE THREAD

**Issue by plundeen** [sabuhish/fastapi-mqtt#46]
The `FastMQTT.match` function does not handle wildcards according to the [MQTT specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718107). Per Section 4.7.1.2:

> "sport/#" also matches the singular "sport", since # includes the parent level.

But the `FastMQTT.match()` method would not consider "sport" a match on the wildcard'ed subscription "sport/#".

**Comment by sabuhish** [comment]
Hello, did your PR solved issue you had?

**Comment by plundeen** [comment]
Yes, thanks!
