### ISSUE TITLE
Wrong package version published

### ISSUE THREAD

**Issue by mblo** [sabuhish/fastapi-mqtt#48]
### Problem

The [recently published version](https://pypi.org/project/fastapi-mqtt/#history) of this package is `1.7`, which does not match the semantic versioning used so far. 
Also, the `pyproject.toml` file holds wrong version, showing `1.0.2` https://github.com/sabuhish/fastapi-mqtt/blob/master/pyproject.toml#L3

### Solution

Re-publish the package as `1.0.7` and withdraw the `1.7` version.

**Comment by sabuhish** [comment]
Sure, I will do it right now thanks for catching this.

**Comment by sabuhish** [comment]
Done, thanks!
