### ISSUE TITLE
Version 1.8 is broken

### ISSUE THREAD

**Issue by grmono** [sabuhish/fastapi-mqtt#56]
It seems that the method  self.client has been changed to  self.config for set_config and results in the below error on startup the problem is cased in line line 140, in __set_connetion_config

`AttributeError: 'MQTTConfig' object has no attribute 'set_config'
`
Also the versioning has changed from 1.0.X to 1.8 for some reason

**Comment by duanyuan-ext** [comment]
I have the same issue

**Comment by sabuhish** [comment]
Right, I did not test it properly, will solve it right now, thanks for the issue.

**Comment by sabuhish** [comment]
should be fixed in 1.0.8 version.
