### ISSUE TITLE
Version 1.0.8 is broken

### ISSUE THREAD

**Issue by AndrewLaptev** [sabuhish/fastapi-mqtt#58]
Hi! 
During startup it showed the following error:

![image](https://github.com/sabuhish/fastapi-mqtt/assets/38818882/618ae713-3d69-4ada-959b-2d6316939504)

As far as I understood, in the last update, `MQTTConfig` was omitted in the body of the `__set_connetion_config` method in the arguments of the `self.client.set_config` method call.  

I fix this in the pull request #57

**Comment by sabuhish** [comment]
Hi, true, I was rushing while working on it, and did not properly touch it, my bad, thanks for opening the issue and solving this issue. Your MR has been merged and released, if everything seems fine, please close the issue. Thanks for your time!
