### ISSUE TITLE
How to use this library with another api endpoint that does something else before return the mqtt topic content in the logic?

### ISSUE THREAD

**Issue by luongngochoa** [sabuhish/fastapi-mqtt#72]
Can anyone provide any example of using this for a api endpoint that register the username and password before run the mqtt subscribe loop
Thanks for contribute.

**Comment by azogue** [comment]
@luongngochoa 

IMHO, that is not the **polite** way of doing that sort of thing...

What you've done is **copy** the code from this repository and store it under a new name in your account, with just 1 'init commit', removing all the **git history** of who, when, and why the code was modified, so now @sabuhish cannot be _git blamed_ (:= _thanked_ 🙏) for anything, and it looks like it's YOUR code, but it's not. 

The code is MIT licensed (so of course you can do whatever you want with it), but please don't expect others to contribute 👎

If you need to operate with a modified version of the code, **make a fork** of it, so it's linked to the original repo, and the git history remains. Then make the changes you need (which can also be checked out for review in the original repo with PRs), and use the code directly from your GitHub account.

If you want to **publish** new versions of the library in pypi, I would ask **why do you need them**?

- If it's for your personal/private usage (you need changes/fixes you already have, but there is no merge/publish from the _official_ library), you can always `pip install` from your favourite repo/branch/special-commit, no need to use versions from pypi. 

  As an example, I'm doing just that while waiting review from my own PRs (#69, #70), and with `poetry`, I have `fastapi-mqtt = { git = "https://github.com/azogue/fastapi-mqtt.git", branch = "target/all-changes" }` in my `pyproject.toml`. It's not ideal (but hopefully temporary), but it does NOT NEED a new release. 

- If it's to publish the work of others in your name, obviously that would be bad. If you are really interested in becoming the maintainer of this library, the first thing would be to politely ASK for it from its author 😜

**Comment by luongngochoa** [comment]
@azogue Ok. Sorry for mistaken. Hope that the owner will soon be back and see your merge request and @ftapajos and then merge them because it will help so much for the usage of someone like me. Thanks so much for contributed.

**Comment by azogue** [comment]
Wow! Now you edited the title and description of the 'issue' and now my answer is totally out of context 🙈👎
