### ISSUE TITLE
Python version < 3.10 TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' 

### ISSUE THREAD

**Issue by Brendan-Taylor** [sabuhish/fastapi-mqtt#85]
fastapi_mqtt/fastmqtt.py, line 52
`mqtt_logger: logging.Logger | None = None,`
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

for python versions less than 3.10

should this be something like:

```
from typing import Union
...
mqtt_logger: Union[logging.Logger,  None] = None,
```

**Comment by azogue** [comment]
Hi @Brendan-Taylor, 

Sorry, I missed that one in the latest release 😓, I'll try to make a quick fix asap, thanks 👍
