### ISSUE TITLE
FastAPI's on_event is deprecated, use lifespan event handlers instead

### ISSUE THREAD

**Issue by mblo** [sabuhish/fastapi-mqtt#87]
FastAPI's `startup` and `shutdown` events are deprecated (https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated).

However, they are still used https://github.com/sabuhish/fastapi-mqtt/blob/d4da8acdf1d6fe06a646cb616582abe06ae16a54/fastapi_mqtt/fastmqtt.py#L231

To resolve this, fastapi-mqtt must use the lifespan events. (There will be no side effect on required version of FastAPI - lifespan events are supported sine 0.93.0)

Please let me know if PR support is required

**Comment by azogue** [comment]
Hi @mblo,

the usage of the `init_app` method is optional

```python
    def init_app(self, app: FastAPI) -> None:  # pragma: no cover
        """Add startup and shutdown event handlers for app without lifespan."""

        @app.on_event("startup")
        async def startup() -> None:
            await self.mqtt_startup()

        @app.on_event("shutdown")
        async def shutdown() -> None:
            await self.mqtt_shutdown()
```

If using lifespan, just call `self.mqtt_startup()` before yielding and `self.mqtt_shutdown()` after 👍

There is an example app in [examples/ws_app/app.py](https://github.com/sabuhish/fastapi-mqtt/blob/master/examples/ws_app/app.py) which is using lifespan.
