### ISSUE TITLE
🚨 Fix GH Action for pypi publish

### ISSUE THREAD

**Issue by azogue** [sabuhish/fastapi-mqtt#88]
cc @sabuhish 

pypi.org has changed their security police 🚨, and using `--username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}` is not valid anymore -> https://github.com/sabuhish/fastapi-mqtt/actions/runs/7396082004/job/20120516144

> HTTP Error 403: Username/Password authentication is no longer supported. Migrate to API Tokens or Trusted Publishers instead. 
> See https://pypi.org/help/#apitoken and https://pypi.org/help/#trusted-publishers
> Access was denied to this resource.

Publish action needs to change, but also the account configuration in pypi.org ⚠️

**Comment by Hecate2** [comment]
(Is it OK to manually publish v2.1.1 to pypi please...?)

**Comment by azogue** [comment]
> (Is it OK to manually publish v2.1.1 to pypi please...?)

Hi @Hecate2 , only @sabuhish can do that 😢

maybe this _ping_ could reach him 🤞

**Comment by sabuhish** [comment]
Hello, thanks for pinging me, just taking care of it, let me check, if not tonight will do it.

**Comment by sabuhish** [comment]
Could you please re-run the actions?  @azogue

**Comment by azogue** [comment]
> Could you please re-run the actions? @azogue

Done ✅

I had to delete the latest release and redo it again to trigger the job (didn't find a 'retry' option), but it worked 🤟

v2.1.1 published: https://pypi.org/project/fastapi-mqtt/  🚀🚀🚀

Closing this issue, thanks @sabuhish 💪
