### ISSUE TITLE
doesn't recognize payload as valid json

### ISSUE THREAD

**Issue by Guggs** [sabuhish/fastapi-mqtt#92]
This just keeps happening and suddenly its gone, without any changes. This only happens with this framework. 
I have to solve it like this: 

json.loads(str(payload.decode())[1:])

So i guess, there is some kind of character in the way, but this:

payload.decode()[0]

gives me an empty string.

**Comment by azogue** [comment]
Hi @Guggs, without the problematic payload this issue has no meaning at all. I can assure you there is no problem with JSON messages 🤷
