### ISSUE TITLE
How to add ssl certificates for handling mqtt with tls for secured communication

### ISSUE THREAD

**Issue by ninjas005** [sabuhish/fastapi-mqtt#93]
I want to deploy my application in production mode.. and one  of my requirement is add encrytpion to the communication with tls layer. I can add certificates in paho-mqtt. how to handle tls layer security in fastapi-mqtt?

**Comment by azogue** [comment]
Hi @ninjas005, the `MQTTConfig` object has an `.ssl` field that you can enable when filling it.

Using it with `ssl=True` + your secure mqtts host + modified port should work ok. Did you have any problem with it?

**Comment by ninjas005** [comment]
I had already did enabling ssl with the `.ssl` field and used port 8883. butit was not able to connect to the broker, but got refused as broker needs the client certificate to pass me through. 
```

mqtt_config = MQTTConfig(host=MQTT_CONFIG['host'],
                             port=MQTT_CONFIG['port'],
                             username=MQTT_CONFIG['user'],
                             password=MQTT_CONFIG['pass'],
                             reconnect_retries=-1,
                             reconnect_delay=30,
                             ssl=True
                             )

    fast_mqtt = FastMQTT(config=mqtt_config)

```
this was my configuration. when i checked the `MQTTConfig` Class it says about a SSLContext Object which will have the `cafile` but I am confused how to add that SSLContext object.

**Comment by azogue** [comment]
> it was not able to connect to the broker, but got refused as broker needs the client certificate to pass me through

The `.ssl` field is defined as `Union[bool, SSLContext]` for that reason. If you need _extra_ data for the TLS/SSL connection, you need to configure the `SSLContext`.

As an example, to connect to https://test.mosquitto.org using port 8883 (MQTT, encrypted, unauthenticated), which requires the cert file, the config should look like this:

```python
from ssl import create_default_context
from fastapi_mqtt import FastMQTT, MQTTConfig

# cert file downloaded from https://test.mosquitto.org/ssl/mosquitto.org.crt
ssl = create_default_context(cafile="tests/mosquitto.org.crt")

mqtt_config = MQTTConfig(host="test.mosquitto.org", port=8883, ssl=ssl)
fast_mqtt = FastMQTT(config=mqtt_config)
```

**Comment by ninjas005** [comment]
ok thank you.

**Comment by azogue** [comment]
Closing this as resolved 👍, ok @ninjas005 ?
